version: '3.8'
 
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: springbootdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3315:3306"
 
  security-application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-creation-container    
    ports:
      - "4321:4321"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3308/springbootdb?useSSL=false
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    restart: always
    env_file:
      - .env

 
volumes:
  mysql_data:
